### ISSUE TITLE
IDX10503: Signature validation failed 

### ISSUE THREAD

**Issue by shimpark** [JBeni/BlazorShop#17]
I found an error in jwt authentication.

'IDX10503: Signature validation failed. Token does not have a kid. Keys tried: 'System.Text.StringBuilder'.\nExceptions caught:\n 'System.Text.StringBuilder'.\ntoken: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.'

`private bool IsCurrentTokenValid(string token)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var isTokenValid = true;

            try
            {
                tokenHandler.ValidateToken(token, new TokenValidationParameters
                {
                    ClockSkew = TimeSpan.FromSeconds(1),
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["JwtToken:SecretKey"])),
                    RequireSignedTokens = true,
                    RequireExpirationTime = true,
                    ValidateLifetime = true,
                    ValidateAudience = false,
                    ValidateIssuer = false,
                    ValidAudience = _configuration["JwtToken:Audience"],
                    ValidIssuer = _configuration["JwtToken:Issuer"]
                }, out SecurityToken validatedToken);
            }
            catch
            {
                isTokenValid = false;
            }

            return isTokenValid;
        }`

**Comment by JBeni** [comment]
Hi,

Thanks for reaching out with the error. I am aware of that.

Unfortunately, I do not have too much time to fix the issue.

Thanks,
Beniamin

**Comment by JBeni** [comment]
**The bug was fixed with this PR**: https://github.com/JBeni/BlazorShop/pull/15
